---
- name: Provision new Auto Scaling Group 
  ec2_asg:
    aws_access_key: '{{ VAULT_AWS_ACCESS_KEY }}'
    aws_secret_key: '{{ VAULT_AWS_SECRET_KEY }}'  
    name: Wordpress-ASG
    launch_config_name: Wordpress-LC
    region: us-east-1   
    health_check_type: ELB
    health_check_period: 300
    desired_capacity: 1
    min_size: 1
    max_size: 2
    state: present
    wait_for_instances: no
    vpc_zone_identifier:
      - '{{ Wordpress_priv_subnet_1.subnet.id }}'
      - '{{ Wordpress_priv_subnet_2.subnet.id }}'  
    target_group_arns: "{{tg.target_group_arn}}"
    tags:
      - Name: Wordpress-EC2
  register: asg_out  
