---
- name : Creating an Application Load Balancer
  elb_application_lb:
    aws_access_key: '{{ VAULT_AWS_ACCESS_KEY }}'
    aws_secret_key: '{{ VAULT_AWS_SECRET_KEY }}'
    name: Wordpress-LB
    security_groups:
            - '{{ alb_sg.group_id }}'
    subnets:
            - '{{ Wordpress_pub_subnet_1.subnet.id }}'
            - '{{ Wordpress_pub_subnet_2.subnet.id }}'
    listeners:
            - Protocol: HTTP
              Port: 8080
              DefaultActions: 
                      - Type: forward
                        TargetGroupName: Wordpress-TG
    state: present 
