- name: Set up private subnet route table
  ec2_vpc_route_table:
    aws_access_key: '{{ VAULT_AWS_ACCESS_KEY }}'
    aws_secret_key: '{{ VAULT_AWS_SECRET_KEY }}'
    vpc_id: '{{wordpress_vpc.vpc.id}}'
    region: us-east-1
    tags:
      Name: Private-RT
    subnets:
      - "{{ Wordpress_priv_subnet_1.subnet.id }}"
      - "{{ Wordpress_priv_subnet_2.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ new_nat_gateway.nat_gateway_id }}"
  register: private_route_table
