---
- name: Bringing up a new AWS Centos server
  ec2:
    aws_access_key: '{{ VAULT_AWS_ACCESS_KEY }}'
    aws_secret_key: '{{ VAULT_AWS_SECRET_KEY }}'
    instance_type: '{{ ec2_instance_type }}'
    image: '{{ ec2_image }}'
    region: '{{ ec2_region }}'
    key_name: '{{ ec2_key_name }}'
    group_id: '{{ ec2_sg.group_id }}'
    vpc_subnet_id: '{{ Wordpress_pub_subnet_1.subnet.id }}'
    instance_profile_name: S3-access-role
    wait: yes
    assign_public_ip: yes
    instance_tags:
      Name:  '{{ ec2_tags_name }}'
    user_data: "{{ lookup('file', 'db.sh') }}"
  register: ec2
- debug: var=ec2.instance_ids[0]
  
- name: Waiting for the Configurations to come up
  local_action: wait_for host={{ item.public_ip }} port=80 state=started
  with_items: "{{ ec2.instances }}"
- name: Add all instance public IPs to host group
  add_host: hostname={{ item.public_ip }} ec2_id={{ item.id }} groups=ec2hosts
  with_items: "{{ ec2.instances }}"
  register: instance

- name: Create AMI
  ec2_ami:
    region: us-east-1
    instance_id: "{{ ec2.instance_ids[0] }}"
    name: wordpress-ami
    wait: yes
    state: present
  register: ami
- debug:
    var: ami.image_id
